version: '3.8'

services:
  # Database
  postgres:
    image: postgres:14-alpine
    container_name: sportsvest-postgres
    environment:
      POSTGRES_DB: sportsvest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/migrations/001_initial_schema.sql:/docker-entrypoint-initdb.d/02-migrations-001.sql
      - ./database/migrations/002_add_indexes.sql:/docker-entrypoint-initdb.d/03-migrations-002.sql
      - ./database/seeds/dev_seed.sql:/docker-entrypoint-initdb.d/04-seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    container_name: sportsvest-api-gateway
    environment:
      - PORT=5000
      - NODE_ENV=development
      - JWT_SECRET=sportsvest_jwt_secret
      - USER_SERVICE_URL=http://user-service:3001
      - TEAM_SERVICE_URL=http://team-service:3002
      - TRADING_SERVICE_URL=http://trading-service:3003
      - COMMUNITY_SERVICE_URL=http://community-service:3005
      - REWARDS_SERVICE_URL=http://rewards-service:3004
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - team-service
      - trading-service
      - community-service
      - rewards-service

  # User Service
  user-service:
    build:
      context: ./services/user-service
    container_name: sportsvest-user-service
    environment:
      - PORT=3001
      - NODE_ENV=development
      - JWT_SECRET=sportsvest_jwt_secret
      - JWT_EXPIRES_IN=24h
      - REFRESH_TOKEN_SECRET=sportsvest_refresh_token_secret
      - REFRESH_TOKEN_EXPIRES_IN=7d
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=sportsvest
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy

  # Team Service
  team-service:
    build:
      context: ./services/team-service
    container_name: sportsvest-team-service
    environment:
      - PORT=3002
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=sportsvest
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "3002:3002"
    depends_on:
      postgres:
        condition: service_healthy

  # Trading Service
  trading-service:
    build:
      context: ./services/trading-service
    container_name: sportsvest-trading-service
    environment:
      - PORT=3003
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=sportsvest
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - TEAM_SERVICE_URL=http://team-service:3002
      - USER_SERVICE_URL=http://user-service:3001
    ports:
      - "3003:3003"
    depends_on:
      postgres:
        condition: service_healthy
      team-service:
        condition: service_started
      user-service:
        condition: service_started

  # Rewards Service
  rewards-service:
    build:
      context: ./services/rewards-service
    container_name: sportsvest-rewards-service
    environment:
      - PORT=3004
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=sportsvest
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - USER_SERVICE_URL=http://user-service:3001
      - TEAM_SERVICE_URL=http://team-service:3002
      - TRADING_SERVICE_URL=http://trading-service:3003
    ports:
      - "3004:3004"
    depends_on:
      postgres:
        condition: service_healthy
      user-service:
        condition: service_started
      team-service:
        condition: service_started
      trading-service:
        condition: service_started

  # Community Service
  community-service:
    build:
      context: ./services/community-service
    container_name: sportsvest-community-service
    environment:
      - PORT=3005
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=sportsvest
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - USER_SERVICE_URL=http://user-service:3001
      - TEAM_SERVICE_URL=http://team-service:3002
    ports:
      - "3005:3005"
    depends_on:
      postgres:
        condition: service_healthy
      user-service:
        condition: service_started
      team-service:
        condition: service_started

  # Frontend
  frontend:
    build:
      context: ./frontend
    container_name: sportsvest-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway

volumes:
  postgres_data: 